name: expenses
description: Managing expenses.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/receipt.png
    - assets/icon/google.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/spending.png"
